language: go

go:
  - 1.7.1

services:
  - rabbitmq
  - redis-server

script: make

# Use Travis' container-based infrastructure:
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

notifications:
  email: false
